apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "d2-prometheus-exporter.fullname" . }}
  labels:
    {{- include "d2-prometheus-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "d2-prometheus-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "d2-prometheus-exporter.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{ if empty .Values.image.tag }}
          image: "{{ .Values.image.repository }}:v{{ .Chart.AppVersion }}"
          {{ else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{ end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PLAYER_PLATFORM
              value: {{ .Values.player.platform | quote }}
            - name: PLAYER_NAME
              value: {{ .Values.player.name | quote }}
            - name: BNET_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bnet_apikey_secret.name | quote }}
                  key: {{ .Values.bnet_apikey_secret.key | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
