apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kove.fullname" . }}
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
{{- if not .Values.serviceAccount }}
  name: {{ include "kove.fullname" . }}
{{- else }}
  name: {{ .Values.serviceAccount }}
{{- end }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
{{- if not .Values.clusterRole }}
  name: {{ include "kove.fullname" . }}
{{- else }}
  name: {{ .Values.clusterRole }}
{{- end }}
  apiGroup: rbac.authorization.k8s.io
