apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kove.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kove.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
