apiVersion: v1
kind: Service
metadata:
  name: {{ include "kove.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kove.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "kove.selectorLabels" . | nindent 4 }}
