{{ if .Values.prometheusOperator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kove.fullname" . }}
  namespace: {{ .Values.prometheusOperator.serviceMonitor.namespace }}
  labels:
{{- if .Values.prometheusOperator.serviceMonitor.selector }}
{{ toYaml .Values.prometheusOperator.serviceMonitor.selector | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "kove.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: {{ .Values.prometheusOperator.serviceMonitor.interval }}
  {{- if .Values.prometheusOperator.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.prometheusOperator.serviceMonitor.scrapeTimeout }}
  {{- end }}
    port: http
  namespaceSelector:
    any: true
{{- end }}
