{{ if not .Values.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kove.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kove.labels" . | nindent 4 }}
{{ end }}
