apiVersion: v1
kind: ConfigMap
metadata:
  name: kove-deprecations-policies
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kove.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob .Values.policyGlob).AsConfig | nindent 2 -}}
